services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    # for mongodb connection string
    env_file:
      - ./.env

  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
    - NEXT_PUBLIC_SERVER_URL=http://localhost:5000
